import type {
  FameEdgeState,
  FameTimeseriesPoint,
  FullMemoryRetentionState,
  GoalGate,
  KnowledgePatchProposal,
  ModuleDebugState,
  PhysicalFeedbackEvent,
  RoutePosteriorState,
  RouteNode,
  Scope,
  SyncOutboxEvent,
  TemporalTruthEdge,
  TraceSpanEvent,
} from './model'

export const defaultScope: Scope = {
  project_id: 'fame-agent-gateway',
  subject: 'knowledge-workbench',
  domain: 'agent-engineering',
  route_id: 'visualization-goalgate-patch',
  task_id: 'initial-workbench-implementation',
}

export const routeNodes: RouteNode[] = [
  {
    id: 'intent-workbench',
    label: '工程现场意图',
    kind: 'intent',
    subject: 'knowledge-workbench',
    route_id: 'visualization-goalgate-patch',
    summary: '把当前工程进度、知识网路线、工具治理和补充入口放进一个可观察工作台。',
    source_ref: '方案设计/08_完整版实施蓝图.md',
    position: { x: 40, y: 110 },
  },
  {
    id: 'association-jianshu',
    label: '建木联想链',
    kind: 'association',
    subject: 'knowledge-workbench',
    route_id: 'visualization-goalgate-patch',
    summary: '从一级联想到抽象层，再走向规则、工具、质量门和返修。',
    source_ref: 'knowledge/BNAI智能agent知识网/knowledge_hierarchy.md',
    position: { x: 300, y: 40 },
  },
  {
    id: 'abstraction-route',
    label: '抽象判型',
    kind: 'abstraction',
    subject: 'knowledge-workbench',
    route_id: 'visualization-goalgate-patch',
    summary: '判断当前问题属于路由、补充、调试、工具治理还是上下文健康。',
    source_ref: 'knowledge/BNAI智能agent知识网/language_tree_links/abstraction_to_expression.yaml',
    position: { x: 560, y: 60 },
  },
  {
    id: 'rule-scope-index',
    label: 'Scope + Index',
    kind: 'rule',
    subject: 'knowledge-workbench',
    route_id: 'visualization-goalgate-patch',
    summary: '所有节点、边、摘要和日志默认按 project_id/subject/route_id/task_id 收敛。',
    source_ref: '方案设计/07_差异化_遍历效率_评估指标.md',
    position: { x: 560, y: 220 },
  },
  {
    id: 'tool-manual',
    label: '一次性工具说明书',
    kind: 'tool',
    subject: 'tool-governance',
    route_id: 'tool-manual-lazy-load',
    summary: '调用前临时加载完整说明，调用后只留下 ToolCallSummary 和 FAME delta。',
    source_ref: '方案设计/01_FAME工程图谱记忆组织器方案.md',
    position: { x: 820, y: 30 },
  },
  {
    id: 'tool-react-flow',
    label: 'React Flow 图编辑',
    kind: 'tool',
    subject: 'knowledge-workbench',
    route_id: 'visualization-goalgate-patch',
    summary: '承担可编辑小图、patch proposal 和遍历路径可视化。',
    source_ref: '方案设计/09_可视化工作台_联想机制_找球门遍历.md',
    position: { x: 820, y: 170 },
  },
  {
    id: 'quality-enforcement',
    label: 'Enforcement Kernel',
    kind: 'quality',
    subject: 'tool-governance',
    route_id: 'enforcement-kernel',
    summary: 'LLM 只提交 ProposedAction，工具网关只接受 ApprovedAction + approval_token。',
    source_ref: '方案设计/01_FAME工程图谱记忆组织器方案.md',
    position: { x: 1080, y: 85 },
  },
  {
    id: 'summary-context',
    label: '上下文健康摘要',
    kind: 'summary',
    subject: 'context-health',
    route_id: 'summary-first',
    summary: '问题解决后释放原始过程，只保留可检索摘要、证据链和下一次提示。',
    source_ref: '方案设计/08_完整版实施蓝图.md',
    position: { x: 1080, y: 250 },
  },
  {
    id: 'lesson-failure',
    label: '失败教训区',
    kind: 'lesson',
    subject: 'tool-governance',
    route_id: 'failure-recurrence-control',
    summary: '高 lambda 代表失败复发风险，应变成教训和修复票据，而不是盲目重试。',
    source_ref: '方案设计/04_FAME公式与参数.md',
    position: { x: 1320, y: 150 },
  },
]

export const fameEdges: FameEdgeState[] = [
  {
    edge_id: 'edge-intent-association',
    source_id: 'intent-workbench',
    target_id: 'association-jianshu',
    relation_type: 'routes_to',
    scope: defaultScope,
    fame: { mu: 0.78, chi: 0.86, epsilon: 0.9, kappa: 0.72, nu: 0.28, delta: 0.08, rho: 0.32, lambda: 0.12 },
    dynamics: { xi: 0.72, freshness: 0.94, half_life_days: 60, last_verified_at: '2026-06-27' },
    evidence: { success_count: 5, failure_count: 0, conflict_count: 0, lesson_count: 1, source_refs: ['09_可视化工作台_联想机制_找球门遍历.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-association-abstraction',
    source_id: 'association-jianshu',
    target_id: 'abstraction-route',
    relation_type: 'supports',
    scope: defaultScope,
    fame: { mu: 0.74, chi: 0.82, epsilon: 0.78, kappa: 0.67, nu: 0.35, delta: 0.18, rho: 0.28, lambda: 0.16 },
    dynamics: { xi: 0.8, freshness: 0.88, half_life_days: 120, last_verified_at: '2026-06-27' },
    evidence: { success_count: 3, failure_count: 1, conflict_count: 0, lesson_count: 1, source_refs: ['knowledge_hierarchy.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-abstraction-scope',
    source_id: 'abstraction-route',
    target_id: 'rule-scope-index',
    relation_type: 'supports',
    scope: defaultScope,
    fame: { mu: 0.82, chi: 0.54, epsilon: 0.86, kappa: 0.8, nu: 0.18, delta: 0.05, rho: 0.2, lambda: 0.08 },
    dynamics: { xi: 0.86, freshness: 0.92, half_life_days: 180, last_verified_at: '2026-06-27' },
    evidence: { success_count: 4, failure_count: 0, conflict_count: 0, lesson_count: 0, source_refs: ['07_差异化_遍历效率_评估指标.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-scope-reactflow',
    source_id: 'rule-scope-index',
    target_id: 'tool-react-flow',
    relation_type: 'uses_tool',
    scope: defaultScope,
    fame: { mu: 0.72, chi: 0.76, epsilon: 0.74, kappa: 0.69, nu: 0.34, delta: 0.12, rho: 0.42, lambda: 0.18 },
    dynamics: { xi: 0.48, freshness: 0.98, half_life_days: 30, last_verified_at: '2026-06-27' },
    evidence: { success_count: 2, failure_count: 0, conflict_count: 0, lesson_count: 0, source_refs: ['React Flow'], log_refs: [] },
  },
  {
    edge_id: 'edge-reactflow-enforcement',
    source_id: 'tool-react-flow',
    target_id: 'quality-enforcement',
    relation_type: 'routes_to',
    scope: defaultScope,
    fame: { mu: 0.68, chi: 0.52, epsilon: 0.82, kappa: 0.63, nu: 0.42, delta: 0.22, rho: 0.36, lambda: 0.2 },
    dynamics: { xi: 0.6, freshness: 0.9, half_life_days: 45, last_verified_at: '2026-06-27' },
    evidence: { success_count: 2, failure_count: 1, conflict_count: 1, lesson_count: 1, source_refs: ['01_FAME工程图谱记忆组织器方案.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-enforcement-summary',
    source_id: 'quality-enforcement',
    target_id: 'summary-context',
    relation_type: 'summarizes_to',
    scope: defaultScope,
    fame: { mu: 0.8, chi: 0.36, epsilon: 0.88, kappa: 0.77, nu: 0.2, delta: 0.06, rho: 0.18, lambda: 0.06 },
    dynamics: { xi: 0.7, freshness: 0.96, half_life_days: 90, last_verified_at: '2026-06-27' },
    evidence: { success_count: 4, failure_count: 0, conflict_count: 0, lesson_count: 1, source_refs: ['08_完整版实施蓝图.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-tool-manual-enforcement',
    source_id: 'tool-manual',
    target_id: 'quality-enforcement',
    relation_type: 'supports',
    scope: { ...defaultScope, subject: 'tool-governance', route_id: 'tool-manual-lazy-load' },
    fame: { mu: 0.84, chi: 0.42, epsilon: 0.8, kappa: 0.82, nu: 0.16, delta: 0.04, rho: 0.18, lambda: 0.05 },
    dynamics: { xi: 0.58, freshness: 0.96, half_life_days: 30, last_verified_at: '2026-06-27' },
    evidence: { success_count: 4, failure_count: 0, conflict_count: 0, lesson_count: 0, source_refs: ['01_FAME工程图谱记忆组织器方案.md'], log_refs: [] },
  },
  {
    edge_id: 'edge-failure-lesson',
    source_id: 'quality-enforcement',
    target_id: 'lesson-failure',
    relation_type: 'fixes_by',
    scope: { ...defaultScope, subject: 'tool-governance', route_id: 'failure-recurrence-control' },
    fame: { mu: 0.46, chi: 0.64, epsilon: 0.7, kappa: 0.44, nu: 0.68, delta: 0.58, rho: 0.54, lambda: 0.76 },
    dynamics: { xi: 0.5, freshness: 0.78, half_life_days: 14, last_verified_at: '2026-06-20' },
    evidence: { success_count: 1, failure_count: 3, conflict_count: 2, lesson_count: 4, source_refs: ['04_FAME公式与参数.md'], log_refs: ['failure_summary/tool_arg_error'] },
  },
]

export const activeGoalGate: GoalGate = {
  gate_id: 'gate-workbench-v0',
  goal_type: 'generate_artifact',
  success_condition: '生成可运行的知识工作台第一版，并能提交知识补充 proposal。',
  required_outputs: ['Route Graph', 'FAME Heatmap', 'Traversal Debug', 'KnowledgePatchProposal', 'Module Debug'],
  quality_gates: ['scope_required', 'proposal_review_required', 'context_summary_required'],
  forbidden_paths: ['full_graph_scan', 'direct_core_knowledge_write', 'tool_without_manual'],
  context_budget: 4800,
}

export const seedProposals: KnowledgePatchProposal[] = [
  {
    proposal_id: 'kpp-seed-001',
    proposer: 'agent',
    target: {
      route_id: 'visualization-goalgate-patch',
      file_path: 'knowledge/BNAI智能agent知识网/knowledge_hierarchy.md',
      section: 'route/visualization',
    },
    patch_type: 'add_edge',
    content_summary: '把可视化工作台加入建木路线：概念 -> 联想 -> 抽象 -> 工具 -> 质量门 -> 摘要回写。',
    evidence_refs: ['方案设计/09_可视化工作台_联想机制_找球门遍历.md'],
    affected_edges: ['edge-intent-association', 'edge-scope-reactflow'],
    initial_fame: { mu: 0.65, chi: 0.82, epsilon: 0.78, kappa: 0.55, nu: 0.35, delta: 0.12, rho: 0.28, lambda: 0.1 },
    review_status: 'proposed',
  },
]

export const moduleDebugStates: ModuleDebugState[] = [
  { module_id: 'knowledge_router', health: 'normal', latency_ms: 18, last_trace_id: 'trace-route-1024', metrics: { route_hit_quality: 0.82, shard_count: 7 } },
  { module_id: 'fame_route_evaluator', health: 'normal', latency_ms: 11, last_trace_id: 'trace-fame-2048', metrics: { calibration_error: 0.12, scored_edges: 8 } },
  { module_id: 'context_health_manager', health: 'normal', latency_ms: 9, last_trace_id: 'trace-context-4096', metrics: { context_token_saving: 0.61, raw_logs_loaded: 0 } },
  { module_id: 'tool_governance_gate', health: 'degraded', latency_ms: 24, last_trace_id: 'trace-tool-8192', metrics: { manual_lookup_success_rate: 0.94, tool_arg_error_rate: 0.07 } },
  { module_id: 'enforcement_kernel', health: 'normal', latency_ms: 15, last_trace_id: 'trace-policy-16384', metrics: { blocked_risk_actions: 3, approved_actions: 12 } },
  { module_id: 'agent_clock_scheduler', health: 'normal', latency_ms: 13, last_trace_id: 'trace-clock-32768', metrics: { scheduler_resume_success_rate: 0.75, stale_routes_found: 1 } },
]

export const fameTimeseriesPoints: FameTimeseriesPoint[] = [
  {
    point_id: 'ftp-edge-intent-association-001',
    edge_id: 'edge-intent-association',
    route_id: defaultScope.route_id,
    project_id: defaultScope.project_id,
    observed_at: '2026-06-27T09:20:00+08:00',
    event_ref: 'trace-route-1024',
    fame: { mu: 0.72, chi: 0.84, epsilon: 0.86, kappa: 0.66, nu: 0.34, delta: 0.1, rho: 0.34, lambda: 0.16 },
    target_fame: { mu: 0.8, chi: 0.86, epsilon: 0.9, kappa: 0.74, nu: 0.24, delta: 0.07, rho: 0.28, lambda: 0.1 },
    inertia_xi: 0.7,
    predicted_delta: 0.06,
    observed_delta: 0.052,
    update_reason: 'verified',
    evidence_refs: ['方案设计/09_可视化工作台_联想机制_找球门遍历.md'],
  },
  {
    point_id: 'ftp-edge-intent-association-002',
    edge_id: 'edge-intent-association',
    route_id: defaultScope.route_id,
    project_id: defaultScope.project_id,
    observed_at: '2026-06-27T12:40:00+08:00',
    event_ref: 'trace-context-4096',
    fame: { mu: 0.78, chi: 0.86, epsilon: 0.9, kappa: 0.72, nu: 0.28, delta: 0.08, rho: 0.32, lambda: 0.12 },
    target_fame: { mu: 0.82, chi: 0.84, epsilon: 0.92, kappa: 0.76, nu: 0.22, delta: 0.06, rho: 0.26, lambda: 0.08 },
    inertia_xi: 0.72,
    predicted_delta: 0.05,
    observed_delta: 0.047,
    update_reason: 'quality_gate',
    evidence_refs: ['workbench build smoke'],
  },
  {
    point_id: 'ftp-edge-failure-lesson-001',
    edge_id: 'edge-failure-lesson',
    route_id: 'failure-recurrence-control',
    project_id: defaultScope.project_id,
    observed_at: '2026-06-27T14:10:00+08:00',
    event_ref: 'failure_summary/tool_arg_error',
    fame: { mu: 0.46, chi: 0.64, epsilon: 0.7, kappa: 0.44, nu: 0.68, delta: 0.58, rho: 0.54, lambda: 0.76 },
    target_fame: { mu: 0.52, chi: 0.68, epsilon: 0.72, kappa: 0.5, nu: 0.5, delta: 0.42, rho: 0.42, lambda: 0.62 },
    inertia_xi: 0.5,
    predicted_delta: 0.09,
    observed_delta: 0.083,
    update_reason: 'failure',
    evidence_refs: ['04_FAME公式与参数.md', 'failure_summary/tool_arg_error'],
  },
]

export const physicalFeedbackEvents: PhysicalFeedbackEvent[] = [
  {
    event_id: 'pfe-build-v13-preview',
    trace_id: 'trace-build-v13-001',
    project_id: defaultScope.project_id,
    route_id: defaultScope.route_id,
    action_id: 'pa-workbench-build',
    feedback_type: 'build',
    status: 'pass',
    distance_before: 0.42,
    distance_after: 0.18,
    kappa_scac: 0.429,
    posterior_entropy_before: 1.42,
    posterior_entropy_after: 0.86,
    feedback_gain: 0.56,
    required_next_step: 'continue selected route and write summary',
    evidence_refs: ['npm run build'],
  },
  {
    event_id: 'pfe-browser-v13-preview',
    trace_id: 'trace-browser-v13-002',
    project_id: defaultScope.project_id,
    route_id: defaultScope.route_id,
    action_id: 'pa-workbench-browser',
    feedback_type: 'browser',
    status: 'pass',
    distance_before: 0.34,
    distance_after: 0.13,
    kappa_scac: 0.382,
    posterior_entropy_before: 0.86,
    posterior_entropy_after: 0.58,
    feedback_gain: 0.28,
    required_next_step: 'keep route posterior and release raw browser logs',
    evidence_refs: ['browser smoke test'],
  },
  {
    event_id: 'pfe-tool-manual-risk',
    trace_id: 'trace-tool-8192',
    project_id: defaultScope.project_id,
    route_id: 'failure-recurrence-control',
    action_id: 'pa-tool-manual',
    feedback_type: 'tool_result',
    status: 'partial',
    distance_before: 0.4,
    distance_after: 0.44,
    kappa_scac: 1.1,
    posterior_entropy_before: 1.08,
    posterior_entropy_after: 1.11,
    feedback_gain: -0.03,
    required_next_step: 're-scope before retry; do not continue the same tool route',
    evidence_refs: ['failure_summary/tool_arg_error'],
  },
]

export const routePosteriorState: RoutePosteriorState = {
  state_id: 'rps-workbench-v13',
  project_id: defaultScope.project_id,
  task_id: 'workbench-v13-full-implementation',
  goal_gate_id: activeGoalGate.gate_id,
  selected_route_id: defaultScope.route_id,
  entropy: 0.58,
  candidates: [
    {
      route_id: defaultScope.route_id,
      label: 'Workbench v13 动态机制路线',
      prior: 0.42,
      posterior: 0.68,
      entropy_contribution: 0.26,
      policy_pass: true,
      last_feedback_ref: 'pfe-build-v13-preview',
      rationale: 'build/browser 反馈收敛，FAME kappa 与 mu 提升。',
    },
    {
      route_id: 'failure-recurrence-control',
      label: '失败复发控制路线',
      prior: 0.28,
      posterior: 0.18,
      entropy_contribution: 0.31,
      policy_pass: true,
      last_feedback_ref: 'pfe-tool-manual-risk',
      rationale: '保留为教训路线，但当前反馈不收敛，不能直接执行。',
    },
    {
      route_id: 'asset-db-light-index-preview',
      label: '资产库轻量索引路线',
      prior: 0.3,
      posterior: 0.14,
      entropy_contribution: 0.25,
      policy_pass: true,
      last_feedback_ref: 'sync-seed-route-table-index-refresh',
      rationale: '资产同步相关，作为支撑路线，不作为主执行路径。',
    },
  ],
}

export const fullMemoryRetentionStates: FullMemoryRetentionState[] = [
  {
    memory_id: 'mem-context-v12-summary',
    memory_type: 'context_summary',
    scope: defaultScope,
    importance: 0.82,
    freshness: 0.96,
    reuse_count: 4,
    full_retention: true,
    context_action: 'include_summary',
    storage_ref: '方案设计/23_Workbench_v12_多模态资产数据库与轻量索引实现记录.md',
    summary_ref: 'summary_memory/workbench-v12.md',
    reason: '全量保留实现记录，本轮上下文只需要读取摘要和验证结论。',
  },
  {
    memory_id: 'mem-failure-tool-args',
    memory_type: 'failure_lesson',
    scope: { ...defaultScope, subject: 'tool-governance', route_id: 'failure-recurrence-control' },
    importance: 0.9,
    freshness: 0.78,
    reuse_count: 3,
    full_retention: true,
    context_action: 'pin_for_goal',
    storage_ref: 'failure_summary/tool_arg_error',
    summary_ref: 'summary_memory/failure-tool-arg-error.md',
    reason: '失败教训必须全量保留，但本轮只把剪枝规则和修复摘要进上下文。',
  },
  {
    memory_id: 'mem-asset-sync-queue',
    memory_type: 'asset_index',
    scope: { ...defaultScope, subject: 'multimodal-asset-store', route_id: 'asset-db-light-index-preview' },
    importance: 0.76,
    freshness: 0.94,
    reuse_count: 2,
    full_retention: true,
    context_action: 'lazy_load_raw',
    storage_ref: 'asset_store/asset_sync_queue.jsonl',
    summary_ref: 'summary_memory/asset-sync-queue.md',
    reason: '同步队列必须可回放全留；只有资产相关 GoalGate 才加载原始队列。',
  },
  {
    memory_id: 'mem-v13-trace',
    memory_type: 'trace',
    scope: { ...defaultScope, task_id: 'workbench-v13-full-implementation' },
    importance: 0.84,
    freshness: 1,
    reuse_count: 1,
    full_retention: true,
    context_action: 'audit_only',
    storage_ref: 'trace/workbench-v13-full-implementation.jsonl',
    summary_ref: 'summary_memory/workbench-v13-trace.md',
    reason: '全链路 trace 用于审计和实机复盘，不长期塞入对话上下文。',
  },
]

export const temporalTruthEdges: TemporalTruthEdge[] = [
  {
    edge_id: 'truth-edge-workbench-v13',
    valid_from: '2026-06-27T00:00:00+08:00',
    valid_to: null,
    observed_at: '2026-06-27T14:30:00+08:00',
    last_verified_at: '2026-06-27T14:30:00+08:00',
    invalidated_by_ref: null,
    status: 'verified_recent',
    provenance_refs: ['方案设计/24_理论论文与外部调研_v13_机制改进建议.md'],
    fame_state_ref: 'edge-intent-association',
  },
  {
    edge_id: 'truth-edge-tool-arg-risk',
    valid_from: '2026-06-20T00:00:00+08:00',
    valid_to: null,
    observed_at: '2026-06-27T14:10:00+08:00',
    last_verified_at: '2026-06-27T14:10:00+08:00',
    invalidated_by_ref: null,
    status: 'unverified_recent',
    provenance_refs: ['failure_summary/tool_arg_error'],
    fame_state_ref: 'edge-failure-lesson',
  },
  {
    edge_id: 'truth-edge-old-static-memory',
    valid_from: '2026-06-01T00:00:00+08:00',
    valid_to: '2026-06-26T23:59:59+08:00',
    observed_at: '2026-06-20T10:00:00+08:00',
    last_verified_at: '2026-06-20T10:00:00+08:00',
    invalidated_by_ref: '方案设计/24_理论论文与外部调研_v13_机制改进建议.md',
    status: 'invalidated',
    provenance_refs: ['legacy static memory note'],
    fame_state_ref: 'edge-enforcement-summary',
  },
]

export const syncOutboxEvents: SyncOutboxEvent[] = [
  {
    outbox_id: 'outbox-sync-route-table-refresh',
    source_proposal_id: 'kpp-seed-001',
    sync_id: 'sync-seed-route-table-index-refresh',
    target: 'asset-route-table-sample',
    operation: 'refresh_asset_index',
    status: 'approved',
    approval_token: 'approved:sync-seed-route-table-index-refresh',
    replayable: true,
    trace_id: 'trace-sync-asset-001',
    reason: 'KnowledgePatchProposal 通过后刷新 route_index 轻量资产索引。',
  },
  {
    outbox_id: 'outbox-sync-fame-paper-review',
    source_proposal_id: 'kpp-fame-paper-review',
    sync_id: 'sync-seed-fame-paper-review',
    target: 'asset-fame-paper-pdf',
    operation: 'verify_asset_refs',
    status: 'pending',
    approval_token: '',
    replayable: true,
    trace_id: 'trace-sync-asset-002',
    reason: 'FAME 论文作为理论证据，需要人工确认 asset refs。',
  },
  {
    outbox_id: 'outbox-sync-runtime-patch',
    source_proposal_id: 'runtime-proposal-preview',
    sync_id: 'sync-runtime-proposal-preview',
    target: 'draft-asset-index',
    operation: 'append_asset_index',
    status: 'blocked',
    approval_token: '',
    replayable: false,
    trace_id: 'trace-sync-asset-003',
    reason: '缺少 ApprovedAction，不能写资产数据库。',
  },
]

export const traceSpanEvents: TraceSpanEvent[] = [
  {
    span_id: 'span-workstart-v13',
    trace_id: 'trace-v13-runtime',
    parent_span_id: null,
    name: 'WorkStartAlignment',
    module_id: 'intent_scope_resolver',
    status: 'ok',
    duration_ms: 12,
    summary: '读取 10/08/09/24 文档并定义 v13 GoalGate。',
  },
  {
    span_id: 'span-route-posterior',
    trace_id: 'trace-v13-runtime',
    parent_span_id: 'span-workstart-v13',
    name: 'RoutePosterior',
    module_id: 'knowledge_router',
    status: 'ok',
    duration_ms: 18,
    summary: '根据 SCAC 反馈更新候选路线后验。',
  },
  {
    span_id: 'span-enforcement',
    trace_id: 'trace-v13-runtime',
    parent_span_id: 'span-route-posterior',
    name: 'EnforcementDecision',
    module_id: 'enforcement_kernel',
    status: 'warn',
    duration_ms: 15,
    summary: '阻断不收敛工具路线，保留为失败教训。',
  },
  {
    span_id: 'span-context-distillation',
    trace_id: 'trace-v13-runtime',
    parent_span_id: 'span-enforcement',
    name: 'ContextDistillation',
    module_id: 'context_health_manager',
    status: 'ok',
    duration_ms: 9,
    summary: '全量记忆保留，仅选择摘要进入本轮上下文。',
  },
]
