param(
  [string]$Repository = "__GITHUB_REPOSITORY__",
  [string]$Version = "latest",
  [string]$InstallDir = "",
  [string]$ArchivePath = "",
  [string]$ChecksumPath = "",
  [string]$AssetPattern = "*portable.zip",
  [string]$NodeVersion = "24.13.0",
  [switch]$Force,
  [switch]$NoStart,
  [switch]$UseSystemNodeOnly,
  [switch]$SkipDependencyInstall
)

$ErrorActionPreference = "Stop"
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new($false)
$OutputEncoding = [Console]::OutputEncoding

function Write-Step {
  param([string]$Message)
  Write-Host "[FAME] $Message"
}

function Resolve-DefaultInstallDir {
  $drives = Get-PSDrive -PSProvider FileSystem |
    Where-Object { $_.Name -ne "C" -and (Test-Path -LiteralPath $_.Root) } |
    Sort-Object Name

  foreach ($drive in $drives) {
    return (Join-Path -Path $drive.Root -ChildPath "FAME\KnowledgeAgentGateway")
  }

  if ($env:LOCALAPPDATA) {
    Write-Warning "No non-system drive was found. Falling back to the current user's local app data directory."
    return (Join-Path -Path $env:LOCALAPPDATA -ChildPath "FAME\KnowledgeAgentGateway")
  }

  throw "Unable to resolve a default install directory. Please pass -InstallDir."
}

function Invoke-FameDownload {
  param(
    [string]$Uri,
    [string]$OutFile
  )
  Write-Step "Downloading $Uri"
  Invoke-WebRequest `
    -Uri $Uri `
    -OutFile $OutFile `
    -UseBasicParsing `
    -Headers @{ "User-Agent" = "fame-knowledge-agent-gateway-installer" }
}

function Get-ReleaseInfo {
  param(
    [string]$Repo,
    [string]$ReleaseVersion
  )
  if ([string]::IsNullOrWhiteSpace($Repo) -or $Repo -eq "__GITHUB_REPOSITORY__") {
    throw "Repository is not configured. Pass -Repository owner/name or use the install.ps1 asset generated by GitHub Actions."
  }

  $releasePath = if ($ReleaseVersion -eq "latest") { "latest" } else { "tags/$ReleaseVersion" }
  $uri = "https://api.github.com/repos/$Repo/releases/$releasePath"
  Write-Step "Resolving GitHub Release $Repo $ReleaseVersion"
  return Invoke-RestMethod `
    -Uri $uri `
    -UseBasicParsing `
    -Headers @{ "User-Agent" = "fame-knowledge-agent-gateway-installer"; "Accept" = "application/vnd.github+json" }
}

function Select-ReleaseAsset {
  param(
    [object]$Release,
    [string]$Pattern
  )
  $asset = @($Release.assets | Where-Object { $_.name -like $Pattern } | Sort-Object name | Select-Object -First 1)
  if (-not $asset) {
    $available = @($Release.assets | ForEach-Object { $_.name }) -join ", "
    throw "No release asset matched '$Pattern'. Available assets: $available"
  }
  return $asset
}

function Test-NodeMajor {
  param([string]$NodeExe)
  try {
    $major = & $NodeExe -p "Number(process.versions.node.split('.')[0])"
    return ([int]$major -ge 24)
  } catch {
    return $false
  }
}

function Resolve-SystemNode {
  $nodeCmd = Get-Command node -ErrorAction SilentlyContinue
  if (-not $nodeCmd) { return $null }
  if (-not (Test-NodeMajor -NodeExe $nodeCmd.Source)) { return $null }

  $npmCmd = Get-Command npm.cmd -ErrorAction SilentlyContinue
  if (-not $npmCmd) {
    $npmCmd = Get-Command npm -ErrorAction SilentlyContinue
  }
  if (-not $npmCmd) { return $null }

  return @{
    Node = $nodeCmd.Source
    Npm = $npmCmd.Source
    PathPrefix = Split-Path -Parent $nodeCmd.Source
    Source = "system"
  }
}

function Resolve-PortableNode {
  param(
    [string]$Root,
    [string]$Version,
    [string]$Stage
  )

  $toolsRoot = Join-Path -Path $Root -ChildPath ".tools"
  $nodeDir = Join-Path -Path $toolsRoot -ChildPath "node-v$Version-win-x64"
  $nodeExe = Join-Path -Path $nodeDir -ChildPath "node.exe"
  $npmExe = Join-Path -Path $nodeDir -ChildPath "npm.cmd"

  if (-not (Test-Path -LiteralPath $nodeExe)) {
    if ($UseSystemNodeOnly) {
      throw "Node.js >= 24 was not found and -UseSystemNodeOnly was set."
    }

    New-Item -ItemType Directory -Force -Path $toolsRoot | Out-Null
    $nodeZip = Join-Path -Path $Stage -ChildPath "node-v$Version-win-x64.zip"
    $nodeUri = "https://nodejs.org/dist/v$Version/node-v$Version-win-x64.zip"
    Invoke-FameDownload -Uri $nodeUri -OutFile $nodeZip
    Expand-Archive -LiteralPath $nodeZip -DestinationPath $toolsRoot -Force
  }

  if (-not (Test-Path -LiteralPath $nodeExe) -or -not (Test-Path -LiteralPath $npmExe)) {
    throw "Portable Node.js was not installed correctly under $nodeDir"
  }

  return @{
    Node = $nodeExe
    Npm = $npmExe
    PathPrefix = $nodeDir
    Source = "portable"
  }
}

function Invoke-Npm {
  param(
    [hashtable]$NodeInfo,
    [string[]]$Arguments,
    [string]$WorkingDirectory
  )
  $oldPath = $env:PATH
  $oldLocation = Get-Location
  try {
    $env:PATH = "$($NodeInfo.PathPrefix);$env:PATH"
    Set-Location -LiteralPath $WorkingDirectory
    Write-Step "npm $($Arguments -join ' ')"
    & $NodeInfo.Npm @Arguments
    if ($LASTEXITCODE -ne 0) {
      throw "npm exited with code $LASTEXITCODE"
    }
  } finally {
    Set-Location -LiteralPath $oldLocation
    $env:PATH = $oldPath
  }
}

function Copy-Payload {
  param(
    [string]$SourceRoot,
    [string]$TargetRoot
  )
  Get-ChildItem -LiteralPath $SourceRoot -Force | ForEach-Object {
    Copy-Item -LiteralPath $_.FullName -Destination (Join-Path -Path $TargetRoot -ChildPath $_.Name) -Recurse -Force
  }
}

if (-not $InstallDir) {
  $InstallDir = Resolve-DefaultInstallDir
}
$InstallDir = [System.IO.Path]::GetFullPath($InstallDir)

Write-Step "Install directory: $InstallDir"
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

$existingItems = @(Get-ChildItem -LiteralPath $InstallDir -Force | Where-Object { $_.Name -ne ".install" })
if ($existingItems.Count -gt 0 -and -not $Force) {
  throw "Install directory is not empty. Pass -Force to overwrite files in place."
}

$stage = Join-Path -Path $InstallDir -ChildPath ".install"
$extractRoot = Join-Path -Path $stage -ChildPath "extract"
Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $stage, $extractRoot | Out-Null

if ($ArchivePath) {
  $zipPath = [System.IO.Path]::GetFullPath($ArchivePath)
  if (-not (Test-Path -LiteralPath $zipPath)) {
    throw "ArchivePath does not exist: $zipPath"
  }
} else {
  $release = Get-ReleaseInfo -Repo $Repository -ReleaseVersion $Version
  $asset = Select-ReleaseAsset -Release $release -Pattern $AssetPattern
  $zipPath = Join-Path -Path $stage -ChildPath $asset.name
  Invoke-FameDownload -Uri $asset.browser_download_url -OutFile $zipPath

  $checksumAsset = @($release.assets | Where-Object { $_.name -eq "$($asset.name).sha256" } | Select-Object -First 1)
  if ($checksumAsset) {
    $ChecksumPath = Join-Path -Path $stage -ChildPath $checksumAsset.name
    Invoke-FameDownload -Uri $checksumAsset.browser_download_url -OutFile $ChecksumPath
  }
}

if ($ChecksumPath) {
  $resolvedChecksumPath = [System.IO.Path]::GetFullPath($ChecksumPath)
  if (Test-Path -LiteralPath $resolvedChecksumPath) {
    $expected = ((Get-Content -LiteralPath $resolvedChecksumPath -Raw) -split "\s+")[0].Trim().ToUpperInvariant()
    $actual = (Get-FileHash -Algorithm SHA256 -LiteralPath $zipPath).Hash.ToUpperInvariant()
    if ($expected -ne $actual) {
      throw "SHA256 mismatch. Expected $expected but got $actual"
    }
    Write-Step "SHA256 verified: $actual"
  }
}

Write-Step "Extracting portable package"
Expand-Archive -LiteralPath $zipPath -DestinationPath $extractRoot -Force

$payloadRoot = $null
if (Test-Path -LiteralPath (Join-Path -Path $extractRoot -ChildPath "package.json")) {
  $payloadRoot = $extractRoot
} else {
  $payloadRoot = Get-ChildItem -LiteralPath $extractRoot -Directory |
    Where-Object { Test-Path -LiteralPath (Join-Path -Path $_.FullName -ChildPath "package.json") } |
    Select-Object -First 1 -ExpandProperty FullName
}
if (-not $payloadRoot) {
  throw "Portable archive does not contain a project package.json."
}

Copy-Payload -SourceRoot $payloadRoot -TargetRoot $InstallDir

$node = Resolve-SystemNode
if (-not $node) {
  $node = Resolve-PortableNode -Root $InstallDir -Version $NodeVersion -Stage $stage
}
Write-Step "Using $($node.Source) Node: $($node.Node)"

if (-not $SkipDependencyInstall) {
  Invoke-Npm -NodeInfo $node -Arguments @("ci", "--prefix", "workbench") -WorkingDirectory $InstallDir
  Invoke-Npm -NodeInfo $node -Arguments @("run", "generate:all") -WorkingDirectory $InstallDir
}

$manifest = @{
  installed_at = (Get-Date).ToUniversalTime().ToString("o")
  install_dir = $InstallDir
  repository = $Repository
  version = $Version
  node_source = $node.Source
  node = $node.Node
  archive = $zipPath
}
$manifest | ConvertTo-Json -Depth 5 | Set-Content -LiteralPath (Join-Path -Path $InstallDir -ChildPath "INSTALL_MANIFEST.json") -Encoding UTF8

Write-Step "Installed successfully."
Write-Step "Workbench: http://127.0.0.1:5178/"
Write-Step "Gateway:   http://127.0.0.1:5191/health"

if (-not $NoStart) {
  Write-Step "Starting FAME Knowledge Agent Gateway"
  $oldPath = $env:PATH
  try {
    $env:PATH = "$($node.PathPrefix);$env:PATH"
    & powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path -Path $InstallDir -ChildPath "start.ps1")
  } finally {
    $env:PATH = $oldPath
  }
}
